### ISSUE TITLE
Insert padding/margin for light/dark button in header

### ISSUE THREAD

**Issue by grasshopper47** [grasshopper47/NFTOpt#43]
Looks crowded:
![image](https://user-images.githubusercontent.com/49437873/170701062-737b9b64-6ad4-4c16-9d8f-971edd0aac42.png)

Something like this is preferred:
![image](https://user-images.githubusercontent.com/49437873/170701216-9fe9f5d5-ba13-436a-a894-0fdffd332939.png)

**Comment by Stefaanna** [comment]
The issue seems to be that scss modules are not loading properly

**Comment by Stefaanna** [comment]
by overriding css styling properly
