### ISSUE TITLE
Styles in the same folder

### ISSUE THREAD

**Issue by grasshopper47** [grasshopper47/NFTOpt#77]
CSS styles are "all over the place"; combine and put in the `styles` folder as highlighted

![image](https://user-images.githubusercontent.com/49437873/170826332-76608921-8add-4679-b97d-00affca4c47d.png)

**Comment by Stefaanna** [comment]
I deliberately structured them like this, because they work like local classes for the file, which can be easily found in the `/styles` subfolder of the corresponding `.tsx` parent.
